### ISSUE TITLE
Tag from metadata author

### ISSUE THREAD

**Issue by DarkVillager** [PreMiD/pmd#96]
Remove the #0000 (tag/discriminator) from the author name in metadata. (create.ts)

**Comment by RisingSunLight42** [comment]
Already resolved here https://github.com/PreMiD/pmd/commit/fb1211ff1c3d03b71505595ed0a887c578694c7b
Update your pmd

**Comment by DarkVillager** [comment]
I updated it yesterday. Same issue.

**Comment by DarkVillager** [comment]
![image](https://user-images.githubusercontent.com/42322979/216953481-f743347d-1d62-4cb9-8120-4b7f9eaf0f26.png)
